export const PUSH_NEW_PARTICIPANTS_INFOS = 'PUSH_NEW_PARTICIPANTS_INFOS'
export const POP_PARTICIPANT_INFOS = 'POP_PARTICIPANT_INFOS'
export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
